In [1]:
import numpy as np 
test = np.arange(12).reshape((3,4))
test

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [2]:
one = np.ones_like(test)
one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [4]:
one.T @ test

array([[12, 15, 18, 21],
       [12, 15, 18, 21],
       [12, 15, 18, 21],
       [12, 15, 18, 21]])

In [13]:
m, n = np.shape(test)
line = np.ones(n)
(test @ line.T).reshape((m,))

array([ 6., 22., 38.])